theme: jekyll-theme-minimal
title: Justin Min
description: Cybersecurity & Regulatory Compliance Specialist
author: Justin Min

# This removes the "View on GitHub" buttons for a cleaner, professional look
show_downloads: false

navigation:
  - title: Home
    url: /index.html
  - title: Projects
    url: /Projects.html
  - title: About Me
    url: /AboutMe.html
  - title: Resume
    url: /documents/Full_Resume.pdf
