theme: jekyll-theme-minimal
title: Justin Min
description: Cybersecurity & Regulatory Compliance Specialist

# Header Links (This creates your navigation)
header_pages:
  - index.md
  - Projects.md
  - AboutMe.md

# This allows us to link to the PDF and Section directly
nav_links:
  - title: Resume
    url: /documents/Full_Resume.pdf
  - title: Contact
    url: /AboutMe.html#contact
