theme: jekyll-theme-minimal
title: Justin Min
description: >
  Cybersecurity & GRC Specialist <br><br>
  <a href="/index.html#contact" style="background-color: #003366; color: white; padding: 8px 15px; border-radius: 5px; text-decoration: none; display: inline-block;">Contact Me</a>

header_pages:
  - index.md
  - Projects.md
  - AboutMe.md

    
