remote_theme: knhash/jekyllBear
plugins:
  - jekyll-remote-theme

title: Justin Min
description: Cybersecurity & Regulatory Compliance Specialist
author: Justin Min

email: justinmin687@gmail.com
linkedin_username: jkunm687
github_username: [YourGitHubUsername]

navigation:
  - title: Home
    url: /index.html
  - title: Projects & Experience
    url: /Projects.html
  - title: About Me
    url: /AboutMe.html
  - title: Resume
    url: /documents/Full_Resume.pdf  
  - title: Contact
    url: /AboutMe.html#contact-me

bear_counters: true
show_description: true

common_head:
  - '<link rel="stylesheet" href="/css/style.css">'
